BASE_URL = 'https://qa-scooter.praktikum-services.ru'
CREATE_COURIER_ENDPOINT_URL = f'{BASE_URL}/api/v1/courier'
LOGIN_COURIER_ENDPOINT_URL = f'{BASE_URL}/api/v1/courier/login'
CREATE_ORDER_ENDPOINT_URL = f'{BASE_URL}/api/v1/orders'
ORDER_LIST_ENDPOINT_URL = f'{BASE_URL}/api/v1/orders'